#!/bin/sh

#
# Normally this is called as '. ./poky-init-build-env /path/to/prebuilt'
#
# This works in most shells (not dash), but not all of them pass arg1 when
# being sourced.   To workaround the shell limitation use "set arg1" prior
# to sourcing this script.
#
if [ -n "$BASH_SOURCE" ]; then
   THIS_SCRIPT_DIR="$(dirname $BASH_SOURCE)"
elif [ -n "$ZSH_NAME" ]; then
   THIS_SCRIPT_DIR="$(dirname $0)"
else
   THIS_SCRIPT_DIR="$(pwd)"
fi

TOP_DIR=$(realpath $THIS_SCRIPT_DIR)
TEMPLATECONF=$TOP_DIR/sources/meta-webos-integration/conf

. $TOP_DIR/sources/poky/oe-init-build-env $TOP_DIR/build
. $TOP_DIR/sources/bitbake-bash-completion/bitbake

export WEBOS_INTEGRATION_PREBUILT_DIR="$1"
export BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE WEBOS_INTEGRATION_PREBUILT_DIR"
